### ISSUE TITLE
#10/11

### ISSUE THREAD

**Issue by Tligtvoet** [Tligtvoet/goat-bulk#14]
An administrator should be able to easily determine whether customers should change their club status, so that they can quickly solve problems provided by Bulk Club members.
Assignee: Mason & Tristan
Estimation: 
Priority: Mid
Completion Definition: The program allows managers to determine whether members should change their Bulk Club status.
Tasks and Tests:
Find a way of determining the benefits of changing Bulk Club Status
Based on the system, give a boolean answer as to whether or not customers should change their status.

**Comment by kencasimiro** [comment]
Kenneth

**Comment by kencasimiro** [comment]
finished half of it

**Comment by kencasimiro** [comment]
done - Kenneth/Mason
