### ISSUE TITLE
#6a

### ISSUE THREAD

**Issue by Tligtvoet** [Tligtvoet/goat-bulk#3]
Any tester will be able to create purchases for new members so that they can verify the integrity of the software.
Assignee: Mason & Tristan
Estimation: 3
Priority: High
Completion Definition: The program has the ability to create standard purchases for new, temporary members.
Tasks and Tests:
Temporary members should be given their own temporary number (T#####)
Special format for file
Temporary members should be given purchases that act the same as a regular purchase
Only difference should be name of the file

**Comment by OverworldLord** [comment]
Can create new members, need purchase function

**Comment by OverworldLord** [comment]
Needs to be integrated

**Comment by kencasimiro** [comment]
done - Mason
