### ISSUE TITLE
#6/7

### ISSUE THREAD

**Issue by Tligtvoet** [Tligtvoet/goat-bulk#4]
Administrators should be empowered to add/delete Bulk Club members from the Bulk Club, as well as items from the inventory list, in order to keep the Bulk Club and it’s items up to date.
Assignee: Kenneth & Mitchell
Estimation: 3
Priority: High
Completion Definition: The program takes administrator input to add or delete members as well as adding items (based on corresponding price) or deleting items.
Tasks and Tests:
Input from a administrator
Ability to add or delete members
Ability to add/delete items
Based on corresponding price

**Comment by OverworldLord** [comment]
Need to save, need to generate inventory list

**Comment by kencasimiro** [comment]
generated inventory list and added add/delete item functionality to the inventory file

**Comment by kencasimiro** [comment]
done by Mason/Kenneth
